package com.MyPTJobs.Services;

import com.MyPTJobs.Class.Employer;
import com.MyPTJobs.Class.FileStorageProperties;
import com.MyPTJobs.Class.FileStorageService;
import com.MyPTJobs.Repository.EmployerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.io.UnsupportedEncodingException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;


@RestController // This means that this class is a Controller
@RequestMapping(path = "/employer") // This means URL's start with /demo (after Application path)
public class EmployerService {
    private final String uploadDir = "Images/Employer/";
    private Path rootLocation;
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EmployerRepository employerRepository;
    @Autowired
    private JobApplicationService jobApplicationService;
    @Autowired
    private JobInterviewService jobInterviewService;

    @Autowired
    private RatingService ratingService;
        
    @Autowired
    private JobSeekerService jobSeekerService;
    @Autowired
    private JobService jobService;
    
    @Autowired
    private ApplicationContext context;

    @Autowired
    private JavaMailSender mailSender;

    @PersistenceContext
    private EntityManager entityManager;


//    public void sendVerificationEmail(Employer employer)
//            throws MessagingException, UnsupportedEncodingException {
//        String toAddress = employer.getEmail();
//        String fromAddress = "myptjobsmy@gmail.com";
//        String senderName = "MyPTJobs";
//        String subject = "Verification Code for Reset Password";
//        String content = "Dear [[name]],<br>"
//                + "Your verification code is: <br>"
//                + "<h3>[[code]]</h3>"
//                + "Thank you,<br>"
//                + "MyPTJobs";
//
//        MimeMessage message = mailSender.createMimeMessage();
//        MimeMessageHelper helper = new MimeMessageHelper(message);
//
//        helper.setFrom(fromAddress, senderName);
//        helper.setTo(toAddress);
//        helper.setSubject(subject);
//
//        content = content.replace("[[name]]", employer.getCompanyName());
//
//        content = content.replace("[[code]]", employer.getVerificationCode());
//
//        helper.setText(content, true);
//
//        mailSender.send(message);
//
//    }
    public void sendVerificationEmail(Employer employer) throws MessagingException, UnsupportedEncodingException {
        String toAddress = employer.getEmail();
        String fromAddress = "myptjobsmy@gmail.com";
        String senderName = "MyPTJobs";
        String subject = "Verification Code for Reset Password, " + employer.getCompanyName();
        String content = "Dear " + employer.getCompanyName() + ",<br><br>"
                + "We hope this email finds you well! As requested, we're sending you the verification code to reset your password.<br><br>"
                + "<h3>" + employer.getVerificationCode() + "</h3><br>"
                + "To reset your password, please follow these steps:<br>"
                + "1) Go to the reset password page<br>"
                + "2) Enter the verification code<br>"
                + "3) Set a new password<br><br>"
                + "If you have any questions or need further assistance, please don't hesitate to contact us at support@myptjobs.com.<br><br>"
                + "Thank you for choosing MyPTJobs!<br><br>"
                + "Best regards,<br>"
                + "MyPTJobs team";

        MimeMessage message = mailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message);

        helper.setFrom(fromAddress, senderName);
        helper.setTo(toAddress);
        helper.setSubject(subject);

        helper.setText(content, true);

        mailSender.send(message);
    }


    public Employer requestEmployerInformation(@RequestParam("id") int id) {
        Optional<Employer> employer = employerRepository.findEmployerByID(id);
        if (employer.isPresent()) {
            return employer.get();
        }
        return new Employer();
    }


    public List<Employer> requestKYBList(String filter) {
        CriteriaBuilder cb = entityManager.getCriteriaBuilder();
        CriteriaQuery<Employer> query = cb.createQuery(Employer.class);
        Root<Employer> root = query.from(Employer.class);
        List<Predicate> predicates = new ArrayList<>();
        // add conditions to the predicates list

        if (!filter.isEmpty()) {
            predicates.add(cb.like(root.get("companyName"), "%" + filter + "%"));
        }

        predicates.add(cb.equal(root.get("verification"), "Pending"));

        // combine the predicates using a logical operator (AND or OR)
        Predicate combinedPredicate = cb.and(predicates.toArray(new Predicate[0]));

        // use constructor expression to select specific attributes
        query.select(cb.construct(Employer.class, root.get("id"), root.get("companyName"), root.get("imageFile"), root.get("verificationDate")));

        query.where(combinedPredicate);

        List<Employer> results = entityManager.createQuery(query).getResultList();
        return results;
    }

    public Employer getKYBVerficationInformation(@RequestParam("id") int id) {
        Optional<Employer> employer = employerRepository.getVerificationInformation(id);
        if (employer.isPresent()) {
            return employer.get();
        }
        return new Employer();
    }


    public boolean updateKYBVerification (int id, String status){
        Optional<Employer> employer = employerRepository.findEmployerByID(id);
        System.out.println(status);
        if (employer.isPresent()) {
            if ( status.equals("Accepted") ){
                employerRepository.updateVerification("Verified", employer.get().getId());
                return true;

            }else if ( status.equals ("Rejected") ){
                employerRepository.updateVerification("Failed", employer.get().getId());
                return true;

            }
            return false;
        } else {
            return false;
        }
    }

    public Employer getEmployerById (int id){
        Optional<Employer> employer = employerRepository.findEmployerByID(id);
        if (employer.isPresent()) {
            return employer.get();
        } else {
            return new Employer();
        }
    }

    public Employer getEmployerByJob (int id){
        Optional<Employer> employer = employerRepository.getEmployerByJob(id);
        if (employer.isPresent()) {
            return employer.get();
        } else {
            return new Employer();
        }
    }

    public List<Employer> getEmployerList(String filter) {
        CriteriaBuilder cb = entityManager.getCriteriaBuilder();
        CriteriaQuery<Employer> query = cb.createQuery(Employer.class);
        Root<Employer> root = query.from(Employer.class);
        List<Predicate> predicates = new ArrayList<>();
        // add conditions to the predicates list

        if (!filter.isEmpty()) {
            predicates.add(cb.like(root.get("companyName"), "%" + filter + "%"));
        }

//        predicates.add(cb.equal(root.get("verification"), "Pending"));

        // combine the predicates using a logical operator (AND or OR)
        Predicate combinedPredicate = cb.and(predicates.toArray(new Predicate[0]));

        // use constructor expression to select specific attributes
        query.select(cb.construct(Employer.class, root.get("id"), root.get("companyName"), root.get("imageFile"), root.get("blockPermanent")));

        query.where(combinedPredicate);

        List<Employer> results = entityManager.createQuery(query).getResultList();
        return results;
    }

    public Employer getEmployerCompanyDescriptionByID (int id){
        Optional<Employer> employer = employerRepository.getCompanyDescriptionByID(id);
        if (employer.isPresent()) {
            return employer.get();
        } else {
            return new Employer();
        }
    }

    public Employer getCompanyInformationByID (int id){
        Optional<Employer> employer = employerRepository.getCompanyInformationByID(id);
        if (employer.isPresent()) {
            return employer.get();
        } else {
            return new Employer();
        }
    }

    public Employer getEmployerOperatingHoursByID (int id){
        Optional<Employer> employer = employerRepository.getOperatingHoursByID(id);
        if (employer.isPresent()) {
            return employer.get();
        } else {
            return new Employer();
        }
    }

    public boolean updateCompanyBackground(Employer emp, Optional<MultipartFile> file, int employerID){
        MultipartFile _file = file.orElse(null);
        Optional<Employer> employer = employerRepository.getCompanyInformationByID(employerID);
        if (!employer.isPresent()) {
            return false;
        }
        String fileName = Integer.toString(employer.get().getId())+"-"+(System.currentTimeMillis() / 1000L);
        try {
//        try (InputStream inputStream = file.getInputStream()){
//            Path filePath = rootLocation.resolve(fileName);
//            Files.copy(inputStream, filePath, StandardCopyOption.REPLACE_EXISTING);
//
//            jobSeeker.setImageFile(fileName);
//            jobSeekerRepository.updateProfile(jobSeeker.getImageFile(),jobSeeker.getName(),jobSeeker.getIC(),jobSeeker.getPhoneNumber(),jobSeeker.getGender(),jobSeeker.getEmploymentStatus(),jobSeeker.getHighestEducation(),jobSeeker.getId());
//
//            return new ResponseEntity<>("Success",HttpStatus.OK);
//            FileStorageService fileService = new FileStorageService(uploadDir);
            if (_file != null) {


                rootLocation = Paths.get(uploadDir);
                if (!Files.exists(rootLocation)) {
                    Files.createDirectories(rootLocation);
                }
                String specificUploadDir =  uploadDir + employer.get().getId()+"/";
                rootLocation = Paths.get(specificUploadDir);
                if (!Files.exists(rootLocation)) {
                    Files.createDirectories(rootLocation);
                }
                FileStorageProperties saveDir = new FileStorageProperties();
                saveDir.setUploadDir(specificUploadDir);
                FileStorageService fileService = new FileStorageService(saveDir);
                fileName = fileService.storeFile(_file, fileName);
                employer.get().setImageFile(employer.get().getId()+"/"+fileName);
            }

            employerRepository.updateInformation(emp.getCompanyName(), emp.getCompanyEmail(), emp.getPhoneNumber(), emp.getLocation(), emp.getSsm(), employer.get().getImageFile(), employer.get().getId(), emp.getState(), emp.getCity());
            Optional<Employer> _employer = employerRepository.getCompanyInformationByID(employerID);
            if (_employer.isPresent()) {
                return true;
            }
            return false;
        } catch (Exception e) {
            System.out.println(e);
            return false;
//            throw new IOException("Could not save uploaded file: " + fileName);
        }

    }

    public void updateCompanyInformation(String description, int employerID){
        employerRepository.updateDescrption(description, employerID);
    }

    public void updateOperatingHours(String operatingHours, int employerID){
        employerRepository.updateOperatingHours(operatingHours, employerID);
    }

    public int getNumberEmployer (){
        return employerRepository.getNumberOfEmployer();
    }

    public int getNumberPendingVerification (){
        return employerRepository.getNumberPendingVerification();
    }

    public void deactive(Employer employer, String blockDate, String type) {
        int permanent = 0;
        if ( type.equalsIgnoreCase("Permanent") ){
            permanent = 1;
        }
        employerRepository.deactive(employer.getId(), blockDate, permanent);
    }

//    public void sendWarning(Employer employer, String title, String contentDetail) throws MessagingException, UnsupportedEncodingException {
//        if ( employer.getEmail() == null || employer.getEmail().isBlank() || employer.getEmail().isEmpty() ){
//            return;
//        }
//        String toAddress = employer.getEmail();
//        String fromAddress = "myptjobsmy@gmail.com";
//        String senderName = "MyPTJobs";
//        String subject = title;
//        String content = "Dear [[name]],<br>" + contentDetail + "<br><br>Thank you,<br>" + "MyPTJobs";
//
//        MimeMessage message = mailSender.createMimeMessage();
//        MimeMessageHelper helper = new MimeMessageHelper(message);
//
//        helper.setFrom(fromAddress, senderName);
//        helper.setTo(toAddress);
//        helper.setSubject(subject);
//
//        content = content.replace("[[name]]", employer.getCompanyName());
////        String verifyURL = siteURL + "/verify?code=" + user.getVerificationCode();
//
//        helper.setText(content, true);
//
//        mailSender.send(message);
//
//    }

    public void sendWarning(Employer employer, String title, String contentDetail, String type) throws MessagingException, UnsupportedEncodingException {
        System.out.println(employer.getEmail());
        if (employer.getEmail() == null || employer.getEmail().isBlank() || employer.getEmail().isEmpty()) {
            return;
        }

        String toAddress = employer.getEmail();
        System.out.println(toAddress);
        String fromAddress = "myptjobsmy@gmail.com";
        String senderName = "MyPTJobs";
        String subject = title;
        String content = "Dear " + employer.getCompanyName() + ",<br><br>"
                + "We have received your complaint regarding the " + type + ". After reviewing the information provided, we have determined that there may be cause for concern.<br><br>We take all complaints seriously and will investigate the issue as soon as possible. Please be advised that false or misleading complaints may result in disciplinary action against the complainant.<br><br>"
                + "Please note that the following reason(s) were provided for your complaint:<br>" + contentDetail
                + "<br><br>Thank you for bringing this matter to our attention. We will contact you if further information is required.<br><br>"
                + "Sincerely,<br>"
                + "MyPTJobs team";

        MimeMessage message = mailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message);

        helper.setFrom(fromAddress, senderName);
        helper.setTo(toAddress);
        helper.setSubject(subject);

        helper.setText(content, true);

        mailSender.send(message);
    }

    public void sendBlockedEmail(Employer employer, String title, String formattedDateTime, String type) throws MessagingException, UnsupportedEncodingException {
        if (employer.getEmail() == null || employer.getEmail().isBlank() || employer.getEmail().isEmpty()) {
            return;
        }

        String toAddress = employer.getEmail();
        String fromAddress = "myptjobsmy@gmail.com";
        String senderName = "MyPTJobs";
        String subject = title;
        String content = "Dear " + employer.getCompanyName() + ",<br><br>";
        content += "<h2>Your account has been blocked</h2>";
        content += "<p>We are sorry to inform you that your account has been blocked due to a violation of our terms and conditions.</p>";
        content += "<p>You will be able to access your account again at " + formattedDateTime + ".</p>";
        content += "<p>If you have any questions or concerns, please do not hesitate to contact us.</p>"
                + "Sincerely,<br>"
                + "MyPTJobs team";

        MimeMessage message = mailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message);

        helper.setFrom(fromAddress, senderName);
        helper.setTo(toAddress);
        helper.setSubject(subject);

        helper.setText(content, true);

        mailSender.send(message);
    }

    public void sendDeletedJob(Employer employer, String title) throws MessagingException, UnsupportedEncodingException {
        if (employer.getEmail() == null || employer.getEmail().isBlank() || employer.getEmail().isEmpty()) {
            return;
        }

        String toAddress = employer.getEmail();
        String fromAddress = "myptjobsmy@gmail.com";
        String senderName = "MyPTJobs";
        String subject = title;
        String content = "Dear " + employer.getCompanyName() + ",<br><br>"
                + "<h2>Your job has been deleted</h2>"
                + "<p>We regret to inform you that your job posting on MyPTJobs has been deleted due to a violation of our terms and conditions.</p>"
                + "<p>If you have any questions or concerns, please do not hesitate to contact us.</p>"
                + "Sincerely,<br>"
                + "MyPTJobs team";

        MimeMessage message = mailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message);

        helper.setFrom(fromAddress, senderName);
        helper.setTo(toAddress);
        helper.setSubject(subject);

        helper.setText(content, true);

        mailSender.send(message);
    }

    public Boolean checkByToken(String token){
        if ( token.isEmpty() ){
            return false;
        }
        Optional<Employer> employer = employerRepository.checkExistingByToken(token);
        if ( employer.isPresent() ){


            return checkBlockOrNot(employer.get());
        }
        return false;
    }


    public boolean checkBlockOrNot(Employer employer){
        long currentTimeMillis = System.currentTimeMillis();
        Timestamp currentTime = new Timestamp(currentTimeMillis);
        if ( (employer.getBlockDate() == null || currentTime.after(employer.getBlockDate())) && employer.getBlockPermanent() == 0 ){
            return true;
        }
        return false;
    }

    public boolean checkCompleteInformationOrNot(Employer employer){
        String completeness = employerRepository.checkEmployerCompleteness(employer.getId());
        if ( completeness.equals("complete") ){
            return true;
        }
        return false;
    }

    public boolean checkVerification(Employer employer){
        String verification = employerRepository.checkEmployerVerification(employer.getId());
        if ( verification.equals("Verified") ){
            return true;
        }
        return false;
    }

}