@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.MyPTJobs.Controllor.JobController#serveFile(String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.MyPTJobs.Controllor.JobController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_858572474 { 
   	label=MyPTJobs
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_127581850 { 
   	label=Controllor
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_631192168 { 
   	label=JobController
	labeljust=l
	fillcolor=white
	style=filled
   
   JobController150600365XXXserveFile1808118735[
	label="+ serveFile()"
	style=filled
	fillcolor=white
	tooltip="JobController

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_1357229392 { 
   	label=Class
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_100655289 { 
   	label=FileStorageService
	labeljust=l
	fillcolor=white
	style=filled
   
   FileStorageService575367491XXXloadFileAsResource1808118735[
	label="+ loadFileAsResource()"
	style=filled
	fillcolor=white
	tooltip="FileStorageService

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
JobController150600365XXXserveFile1808118735 -> FileStorageService575367491XXXloadFileAsResource1808118735;
    
}
@enduml